/// Flutter icons WeatherIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';
  static const String? _kFontPkg = null;

  static const IconData cloud_flash_inv = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_inv = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xf0c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun = IconData(0xf6c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xf72e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_showers_heavy = IconData(0xf740, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun_rain = IconData(0xf743, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
